---
- hosts: localhost
  connection: local
  vars:
    access: redactedxxx 
    secret: redactedyyy
    instance_name: cloudcat-cracker
    image: ami-0ee246e709782b1be
    region: regionxxx
    type: typexxx
    ssh_key: sshxxx
    identity: identityxxx
    wordsnap: snapxxx
    #group:
  vars_files:
    - external_vars.yml

  tasks:
    - name: Gathering EC2 instance information
      ec2_instance_facts:
        aws_access_key: "{{ access }}"
        aws_secret_key: "{{ secret }}"
        region: "{{ region }}"
        filters:
          "tag:name": cloudcat-instance
      register: ec2

    - debug:
        msg: "EC2 instance {{ ec2.instances.0.instance_id }} at {{ ec2.instances.0.public_ip_address }} will be destroyed."
      ignore_errors: true

    - name: Destroying EC2 instance
      ec2_instance:
        aws_access_key: "{{ access }}"
        aws_secret_key: "{{ secret }}"
        state: absent
        instance_ids: "{{ ec2.instances.0.instance_id }}"
        region: "{{ region }}"
        wait_timeout: "300"
        wait: true
      register: ec2
      ignore_errors: true

    - debug:
        msg: "EC2 instance destroyed."
    
    - name: Gathering volume facts
      ec2_vol_facts:
        aws_access_key: "{{ access }}"
        aws_secret_key: "{{ secret }}"
        region: "{{ region }}"
        filters:
          "tag:name": "cloudcat-wordlist"
      register: ec2vol
              
    - name: Destroying wordlist volume
      ec2_vol:
        aws_access_key: "{{ access }}"
        aws_secret_key: "{{ secret }}"
        state: absent
        region: "{{ region }}"
        id: "{{ ec2vol.volumes.0.id }}"

    - debug:
        msg: "Wordlist volume {{ ec2vol.volumes.0.id }} destroyed."

    - debug:
        msg: "All instances and wordlists destroyed."

    - name: Checking for remaining instances
      ec2_instance_facts:
        aws_access_key: "{{ access }}"
        aws_secret_key: "{{ secret }}"
        region: "{{ region }}"
        filters:
          "tag:name": cloudcat-instance
          instance-state-name: [ "shutting-down", "stopping", "stopped", "terminated" ]
      register: remaining

    - debug:
        msg: "{{ remaining.instances.0.instance_id }} instance(s) remaining."
      when: remaining is defined

    - debug:
        msg: "No instances remaining relating to CloudCat."
      when: remaining is undefined
